<?xml version="1.0" encoding="UTF-8"?>
<project version="4">
  <component name="dataSourceStorageLocal">
    <data-source name="Django default" uuid="88bbf378-ee6b-44f1-b9b9-76fb8144d8ef">
      <database-info product="" version="" jdbc-version="" driver-name="" driver-version="" />
      <first-sync>true</first-sync>
      <user-name>root</user-name>
    </data-source>
    <data-source name="python_cagaileo@192.168.99.100" uuid="facac2ce-82c3-4361-a98b-df7128e63c40">
      <database-info product="MySQL" version="5.7.20-0ubuntu0.16.04.1" jdbc-version="4.0" driver-name="MySQL Connector Java" driver-version="mysql-connector-java-5.1.44 ( Revision: b3cda4f864902ffdde495b9df93937c3e20009be )">
        <extra-name-characters>#@</extra-name-characters>
        <identifier-quote-string>`</identifier-quote-string>
      </database-info>
      <case-sensitivity plain-identifiers="exact" quoted-identifiers="exact" />
      <secret-storage>master_key</secret-storage>
      <user-name>root</user-name>
      <introspection-schemas>*:python_cagaileo</introspection-schemas>
    </data-source>
  </component>
</project>